import { StyleSheet } from 'react-native';
import COLORS from './colors';

const styles = StyleSheet.create({
  //please short from a to z or by categori if adding styles

  //Single Styles
  alItCenter: { alignItems: 'center' },
  alItStart: { alignItems: 'flex-start' },
  br0: { borderRadius: 0 },
  br10: { borderRadius: 10 },
  br100: { borderRadius: 100 },
  fx1: { flex: 1 },
  fx3: { flex: 3 },
  fx4: { flex: 4 },
  fxGrow: { flexGrow: 1 },
  justCenter: { justifyContent: 'center' },
  justEnd: { justifyContent: 'flex-end' },
  mr8: { margin: 8 },
  mr12: { margin: 12 },
  mr16: { margin: 16 },
  mrb4: { marginBottom: 4 },
  mrb8: { marginBottom: 8 },
  mrb12: { marginBottom: 12 },
  mrb16: { marginBottom: 16 },
  mrb20: { marginBottom: 20 },
  mrb24: { marginBottom: 24 },
  mrb36: { marginBottom: 36 },
  mrh4: { marginHorizontal: 4 },
  mrh8: { marginHorizontal: 8 },
  mrh12: { marginHorizontal: 12 },
  mrl4: { marginLeft: 4 },
  mrl8: { marginLeft: 8 },
  mrl12: { marginLeft: 12 },
  mrl16: { marginLeft: 16 },
  mrr4: { marginRight: 4 },
  mrr8: { marginRight: 8 },
  mrr12: { marginRight: 12 },
  mrr16: { marginRight: 16 },
  mrt4: { marginTop: 4 },
  mrt12: { marginTop: 12 },
  mrt20: { marginTop: 20 },
  mrv16: { marginVertical: 16 },
  pd0: { padding: 0 },
  pd12: { padding: 12 },
  pd10: { padding: 10 },
  pd16: { padding: 16 },
  pdh0: { paddingHorizontal: 0 },
  pdh4: { paddingHorizontal: 4 },
  pdh8: { paddingHorizontal: 8 },
  pdh12: { paddingHorizontal: 12 },
  pdh16: { paddingHorizontal: 16 },
  pdh24: { paddingHorizontal: 24 },
  pdv4: { paddingVertical: 4 },
  pdv8: { paddingVertical: 8 },
  pdv12: { paddingVertical: 12 },
  pdv16: { paddingVertical: 16 },
  pdv24: { paddingVertical: 24 },
  row: { flexDirection: 'row' },
  spaceBtwn: { justifyContent: 'space-between' },
  txtCapitalize: { textTransform: 'capitalize' },
  txtDecLineT: { textDecorationLine: 'line-through' },
  txtCenter: { textAlign: 'center' },
  txtUppercase: { textTransform: 'uppercase' },
  w100: { width: '100%' },
  h100: { height: '100%' },

  //Custom Styles
  borBtmLine: { borderBottomWidth: 1, borderBottomColor: COLORS.black30 },
  rowAlgCenter: { flexDirection: 'row', alignItems: 'center' },
});

export default styles;
